import json
import os

import requests
from dotenv import load_dotenv
from pydantic import Field

from agency_swarm.tools import BaseTool

load_dotenv()


class TelegramSendVoice(BaseTool):
    """
    Sends a voice message to a Telegram chat.
    Used to send voice confirmations generated by ElevenLabs.
    """

    chat_id: str = Field(..., description="Telegram chat ID to send voice message to")

    voice_file_path: str = Field(..., description="Local path to the voice file (OGG or MP3 format)")

    caption: str = Field(default="", description="Optional text caption for the voice message")

    duration: int = Field(default=0, description="Optional duration of the voice message in seconds")

    def run(self):
        """
        Sends the voice message via Telegram Bot API.
        Returns JSON string with message details.
        """
        bot_token = os.getenv("TELEGRAM_BOT_TOKEN")
        if not bot_token:
            return json.dumps({"error": "TELEGRAM_BOT_TOKEN not found in environment variables"})

        # Check if file exists
        if not os.path.exists(self.voice_file_path):
            return json.dumps({"error": f"Voice file not found at path: {self.voice_file_path}"})

        try:
            url = f"https://api.telegram.org/bot{bot_token}/sendVoice"

            # Prepare form data
            data = {"chat_id": self.chat_id}

            if self.caption:
                data["caption"] = self.caption

            if self.duration > 0:
                data["duration"] = self.duration

            # Open and send file
            with open(self.voice_file_path, "rb") as voice_file:
                files = {"voice": voice_file}

                response = requests.post(url, data=data, files=files, timeout=60)
                response.raise_for_status()

            response_data = response.json()

            if not response_data.get("ok"):
                return json.dumps({"error": f"Telegram API error: {response_data.get('description', 'Unknown error')}"})

            result = {
                "success": True,
                "message_id": response_data["result"]["message_id"],
                "chat_id": response_data["result"]["chat"]["id"],
                "file_id": response_data["result"]["voice"]["file_id"],
                "duration": response_data["result"]["voice"].get("duration", 0),
                "file_size": response_data["result"]["voice"].get("file_size", 0),
                "sent_file": self.voice_file_path,
            }

            return json.dumps(result, indent=2)

        except requests.exceptions.RequestException as e:
            return json.dumps({"error": f"Failed to send voice message: {str(e)}"})
        except Exception as e:
            return json.dumps({"error": f"Error sending voice: {str(e)}"})


if __name__ == "__main__":
    print("Testing TelegramSendVoice...")

    # Test 1: Check for token
    print("\n1. Check TELEGRAM_BOT_TOKEN:")
    token = os.getenv("TELEGRAM_BOT_TOKEN")
    if token:
        print(f"Token found (starts with): {token[:10]}...")
    else:
        print("Warning: TELEGRAM_BOT_TOKEN not set")

    # Test 2: Try to send (will fail without valid file)
    print("\n2. Test send voice (will fail without file):")
    tool = TelegramSendVoice(chat_id="12345", voice_file_path="/tmp/test_voice.ogg", caption="Test voice message")
    result = tool.run()
    print(result)

    print("\nTest completed!")
    print("\nUsage notes:")
    print("- Generate voice file using ElevenLabsTextToSpeech first")
    print("- Voice file should be in OGG or MP3 format")
    print("- Telegram will show the voice message with a play button")
    print("- Optional: Add caption for context")
