name: Test Production Secrets Configuration

on:
  workflow_dispatch:  # Manual trigger for testing
    inputs:
      environment:
        description: 'Environment to test'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/test-production-secrets.yml'
      - 'docs/github_secrets_setup.md'

jobs:
  test-secrets:
    name: Test Required Secrets
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx requests

      - name: Check Required Secrets Availability
        run: |
          echo "🔍 Checking required production secrets..."
          
          # Check OPENAI_API_KEY
          if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "✅ OPENAI_API_KEY is configured"
            # Validate format (should start with sk-)
            if [[ "${{ secrets.OPENAI_API_KEY }}" == sk-* ]]; then
              echo "✅ OPENAI_API_KEY has valid format"
            else
              echo "❌ OPENAI_API_KEY format appears invalid (should start with 'sk-')"
              exit 1
            fi
          else
            echo "❌ OPENAI_API_KEY is missing"
            exit 1
          fi
          
          # Check APP_TOKEN
          if [ -n "${{ secrets.APP_TOKEN }}" ]; then
            echo "✅ APP_TOKEN is configured"
            # Check minimum length (should be 32+ characters)
            if [ ${#{{ secrets.APP_TOKEN }} -ge 32 ]; then
              echo "✅ APP_TOKEN has sufficient length"
            else
              echo "⚠️ APP_TOKEN is shorter than recommended (32+ characters)"
            fi
          else
            echo "❌ APP_TOKEN is missing"
            exit 1
          fi
          
          # Check Docker credentials
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "✅ DOCKER_USERNAME is configured"
          else
            echo "❌ DOCKER_USERNAME is missing"
            exit 1
          fi
          
          if [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "✅ DOCKER_PASSWORD is configured"
          else
            echo "❌ DOCKER_PASSWORD is missing"
            exit 1
          fi

      - name: Check Optional Secrets
        run: |
          echo "🔍 Checking optional production secrets..."
          
          # SSL Certificates
          if [ -n "${{ secrets.SSL_KEYFILE_CONTENT }}" ]; then
            echo "✅ SSL_KEYFILE_CONTENT is configured"
          else
            echo "ℹ️ SSL_KEYFILE_CONTENT is not configured (optional)"
          fi
          
          if [ -n "${{ secrets.SSL_CERTFILE_CONTENT }}" ]; then
            echo "✅ SSL_CERTFILE_CONTENT is configured"
          else
            echo "ℹ️ SSL_CERTFILE_CONTENT is not configured (optional)"
          fi
          
          # Alert webhook
          if [ -n "${{ secrets.ALERT_WEBHOOK_URL }}" ]; then
            echo "✅ ALERT_WEBHOOK_URL is configured"
          else
            echo "ℹ️ ALERT_WEBHOOK_URL is not configured (optional)"
          fi
          
          # Database URL
          if [ -n "${{ secrets.DATABASE_URL }}" ]; then
            echo "✅ DATABASE_URL is configured"
          else
            echo "ℹ️ DATABASE_URL is not configured (optional)"
          fi

      - name: Test OpenAI API Connection
        run: |
          echo "🧪 Testing OpenAI API connection..."
          python3 << 'EOF'
          import httpx
          import sys
          import os
          
          api_key = "${{ secrets.OPENAI_API_KEY }}"
          
          try:
              headers = {"Authorization": f"Bearer {api_key}"}
              response = httpx.get("https://api.openai.com/v1/models", headers=headers, timeout=10)
              
              if response.status_code == 200:
                  print("✅ OpenAI API connection successful")
                  models = response.json()
                  print(f"✅ Available models: {len(models.get('data', []))} models found")
              elif response.status_code == 401:
                  print("❌ OpenAI API authentication failed - check API key")
                  sys.exit(1)
              else:
                  print(f"⚠️ OpenAI API returned status {response.status_code}")
                  print(f"Response: {response.text}")
                  sys.exit(1)
                  
          except Exception as e:
              print(f"❌ OpenAI API connection failed: {e}")
              sys.exit(1)
          EOF

      - name: Test Docker Hub Authentication
        run: |
          echo "🧪 Testing Docker Hub authentication..."
          
          # Test Docker login (without actually logging in to avoid rate limits)
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin 2>&1 | grep -q "Login Succeeded" && {
            echo "✅ Docker Hub authentication successful"
            docker logout
          } || {
            echo "❌ Docker Hub authentication failed"
            exit 1
          }

      - name: Test SSL Certificate Format (if provided)
        if: ${{ secrets.SSL_KEYFILE_CONTENT != '' && secrets.SSL_CERTFILE_CONTENT != '' }}
        run: |
          echo "🧪 Testing SSL certificate format..."
          
          # Test SSL key format
          echo "${{ secrets.SSL_KEYFILE_CONTENT }}" | base64 -d > test_key.pem 2>/dev/null && {
            echo "✅ SSL private key is valid base64"
            # Check if it's a valid private key
            openssl rsa -in test_key.pem -check -noout 2>/dev/null && {
              echo "✅ SSL private key format is valid"
            } || {
              echo "⚠️ SSL private key format may be invalid"
            }
            rm -f test_key.pem
          } || {
            echo "❌ SSL private key is not valid base64"
            exit 1
          }
          
          # Test SSL certificate format
          echo "${{ secrets.SSL_CERTFILE_CONTENT }}" | base64 -d > test_cert.pem 2>/dev/null && {
            echo "✅ SSL certificate is valid base64"
            # Check if it's a valid certificate
            openssl x509 -in test_cert.pem -text -noout 2>/dev/null && {
              echo "✅ SSL certificate format is valid"
              # Check expiration
              expiry=$(openssl x509 -in test_cert.pem -enddate -noout | cut -d= -f2)
              echo "ℹ️ SSL certificate expires: $expiry"
            } || {
              echo "⚠️ SSL certificate format may be invalid"
            }
            rm -f test_cert.pem
          } || {
            echo "❌ SSL certificate is not valid base64"
            exit 1
          }

      - name: Test Alert Webhook (if provided)
        if: ${{ secrets.ALERT_WEBHOOK_URL != '' }}
        run: |
          echo "🧪 Testing alert webhook..."
          
          python3 << 'EOF'
          import httpx
          import json
          import sys
          
          webhook_url = "${{ secrets.ALERT_WEBHOOK_URL }}"
          
          # Test payload for different webhook types
          if "slack.com" in webhook_url:
              payload = {"text": "🧪 GitHub Actions secrets test - Slack webhook working!"}
          elif "discord.com" in webhook_url:
              payload = {"content": "🧪 GitHub Actions secrets test - Discord webhook working!"}
          else:
              payload = {"message": "🧪 GitHub Actions secrets test - Generic webhook working!"}
          
          try:
              response = httpx.post(webhook_url, json=payload, timeout=10)
              if response.status_code in [200, 204]:
                  print("✅ Alert webhook test successful")
              else:
                  print(f"⚠️ Alert webhook returned status {response.status_code}")
                  print(f"Response: {response.text}")
          except Exception as e:
              print(f"❌ Alert webhook test failed: {e}")
              # Don't fail the workflow for webhook issues
          EOF

      - name: Generate Security Report
        run: |
          echo "📊 Security Configuration Report"
          echo "================================"
          echo "Environment: ${{ github.event.inputs.environment || 'staging' }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo ""
          echo "✅ All required secrets are properly configured"
          echo "✅ OpenAI API connection is working"
          echo "✅ Docker Hub authentication is working"
          echo ""
          echo "🔐 Security Recommendations:"
          echo "- Rotate secrets every 90 days"
          echo "- Use different secrets for staging/production"
          echo "- Monitor secret usage in audit logs"
          echo "- Keep backup of APP_TOKEN in secure location"
          echo ""
          echo "📚 Next Steps:"
          echo "1. Deploy to staging environment first"
          echo "2. Test all monitoring endpoints"
          echo "3. Verify error alerting works"
          echo "4. Run load tests with rate limiting"
          echo "5. Deploy to production"

      - name: Success Notification
        run: |
          echo "🎉 All production secrets are properly configured!"
          echo "Your Agency Swarm deployment is ready for production."
