name: Validate Secrets Syntax

on:
  workflow_dispatch:  # Manual trigger only
  
jobs:
  validate-syntax:
    name: Validate GitHub Actions Secrets Syntax
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test secrets context access patterns
        env:
          # Test all the patterns used in the main workflow
          TEST_OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          TEST_APP_TOKEN: ${{ secrets.APP_TOKEN }}
          TEST_DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          TEST_DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
          TEST_SSL_KEY: ${{ secrets.SSL_KEYFILE_CONTENT }}
          TEST_SSL_CERT: ${{ secrets.SSL_CERTFILE_CONTENT }}
          TEST_WEBHOOK: ${{ secrets.ALERT_WEBHOOK_URL }}
          TEST_DB_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "🧪 Testing secrets context access patterns..."
          
          # Test environment variable access
          if [ -n "$TEST_OPENAI_KEY" ]; then
            echo "✅ OPENAI_API_KEY context access works"
          else
            echo "ℹ️ OPENAI_API_KEY not set (expected for validation)"
          fi
          
          if [ -n "$TEST_APP_TOKEN" ]; then
            echo "✅ APP_TOKEN context access works"
          else
            echo "ℹ️ APP_TOKEN not set (expected for validation)"
          fi
          
          echo "✅ All secrets context patterns are syntactically valid"

      - name: Test conditional expressions
        if: ${{ secrets.OPENAI_API_KEY || true }}  # Always run for syntax validation
        run: |
          echo "✅ Conditional expression syntax is valid"

      - name: Test SSL conditional (always false for validation)
        if: ${{ secrets.SSL_KEYFILE_CONTENT && secrets.SSL_CERTFILE_CONTENT }}
        run: |
          echo "✅ SSL conditional syntax is valid"

      - name: Test webhook conditional (always false for validation)  
        if: ${{ secrets.ALERT_WEBHOOK_URL }}
        run: |
          echo "✅ Webhook conditional syntax is valid"

      - name: Validation complete
        run: |
          echo "🎉 All GitHub Actions secrets syntax patterns are valid!"
          echo "✅ Environment variable access: Working"
          echo "✅ Conditional expressions: Working"  
          echo "✅ Secret context access: Working"
          echo ""
          echo "The main test-production-secrets.yml workflow should now work correctly."
